# Generated by Django 5.2.17 on 2026-09-21 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_bn', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(default='🐟', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_bn', models.CharField(max_length=100)),
                ('charge', models.FloatField(default=100.0)),
                ('days', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_bn', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('price_per_kg', models.FloatField(default=0.0)),
                ('stock_kg', models.FloatField(default=0.0)),
                ('region', models.CharField(blank=True, default='', max_length=150)),
                ('freshness_hours', models.IntegerField(default=12)),
                ('cleaning_options', models.JSONField(default=list)),
                ('rating', models.FloatField(default=4.8)),
                ('reviews', models.IntegerField(default=0)),
                ('img', models.TextField(blank=True, default='')),
                ('is_featured', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
